### ISSUE TITLE
wp2 checklist

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/voicecommand-demo#1]
Hi, here the usual wp2 checklist, please tick everything that is already addressed, feel free to ping me if you need help.

- [x] Does the project have a `README.md` ?
- [ ] Does the project have a `LICENSE` file?
    - If possible use either [MIT](https://spdx.org/licenses/MIT) or other compatible licenses.
- [ ] Does the project have a [GitHub Action](https://github.com/features/actions) (you may use [sifis-generate](https://crates.io/crates/sifis-generate) to create it)?
    - [ ] Does it upload the code coverage somewhere?
    - [ ] Does it manage the release of the code? (Continuous Delivery)
- [ ] Does it have a DockerFile or does it need it?

## Bonus track

- [ ] Does it use [poetry](https://python-poetry.org/docs/basic-usage/)?
- [ ] Does it pass [ruff](https://github.com/charliermarsh/ruff) lints?
- [ ] Will you deploy it to pypi?
